"🎨 package: ui":
  - any: ["packages/ui/**"]

"✏️ package: ui-utils":
  - any: ["packages/ui-utils/**"]

"🔨 package: utils":
  - any: ["packages/utils/**"]

"🔧 package: tailwind-config":
  - any: ["packages/tailwind-config/**"]

"🧰 package: tsconfig":
  - any: ["packages/tsconfig/**"]

"🚀 docs":
  - any: ["apps/docs/**"]

"🎮 playground":
  - any: ["playground/**"]
